#!/bin/ksh
#
set -x
export WRFPATH=$wrfpath
export UNIPOST_HOME=$unipost_home
export POSTEXEC=$${UNIPOST_HOME}/bin
export tag=NCAR
fhr=`printf "%02i" $fhr`
domain=$domain
export NEWDATE=$startdate
export tmmark=tm00
export MP_SHARED_MEMORY=yes
export MP_LABELIO=yes
cd $postdir
ln -fs $${WRFPATH}/run/ETAMPNEW_DATA nam_micro_lookup.dat
ln -fs $${WRFPATH}/run/ETAMPNEW_DATA.expanded_rain hires_micro_lookup.dat
ln -fs $${UNIPOST_HOME}/parm/post_avblflds.xml post_avblflds.xml
ln -fs $${UNIPOST_HOME}/src/lib/g2tmpl/params_grib2_tbl_new params_grib2_tbl_new
CRTMDIR=$${UNIPOST_HOME}/src/lib/crtm2/src/fix
ln -fs $$CRTMDIR/EmisCoeff/Big_Endian/EmisCoeff.bin           ./
ln -fs $$CRTMDIR/AerosolCoeff/Big_Endian/AerosolCoeff.bin     ./
ln -fs $$CRTMDIR/CloudCoeff/Big_Endian/CloudCoeff.bin         ./
ln -fs $$CRTMDIR/SpcCoeff/Big_Endian/imgr_g12.SpcCoeff.bin    ./
ln -fs $$CRTMDIR/TauCoeff/ODPS/Big_Endian/imgr_g12.TauCoeff.bin    ./
ln -fs $$CRTMDIR/SpcCoeff/Big_Endian/imgr_g11.SpcCoeff.bin    ./
ln -fs $$CRTMDIR/TauCoeff/ODPS/Big_Endian/imgr_g11.TauCoeff.bin    ./
ln -fs $$CRTMDIR/SpcCoeff/Big_Endian/amsre_aqua.SpcCoeff.bin  ./
ln -fs $$CRTMDIR/TauCoeff/ODPS/Big_Endian/amsre_aqua.TauCoeff.bin  ./
ln -fs $$CRTMDIR/SpcCoeff/Big_Endian/tmi_trmm.SpcCoeff.bin    ./
ln -fs $$CRTMDIR/TauCoeff/ODPS/Big_Endian/tmi_trmm.TauCoeff.bin    ./
ln -fs $$CRTMDIR/SpcCoeff/Big_Endian/ssmi_f15.SpcCoeff.bin    ./
ln -fs $$CRTMDIR/TauCoeff/ODPS/Big_Endian/ssmi_f15.TauCoeff.bin    ./
ln -fs $$CRTMDIR/SpcCoeff/Big_Endian/ssmis_f20.SpcCoeff.bin   ./
ln -fs $$CRTMDIR/TauCoeff/ODPS/Big_Endian/ssmis_f20.TauCoeff.bin   ./
ln -fs $$CRTMDIR/SpcCoeff/Big_Endian/ssmis_f17.SpcCoeff.bin   ./
ln -fs $$CRTMDIR/TauCoeff/ODPS/Big_Endian/ssmis_f17.TauCoeff.bin   ./
cat > itag <<EOF
$wrfout_filename
netcdf
$time_suffix
$${tag}
EOF
rm fort.*
cp $wrf_parm_filename wrf_cntrl.parm
ln -sf wrf_cntrl.parm fort.14
#aprun -B $${POSTEXEC}/unipost.exe > upplog.txt
#aprun -B $${POSTEXEC}/unipost.exe > unipost.$${fhr}.out 2>&1
aprun -B $${POSTEXEC}/unipost.exe > unipost_$${domain}.$${fhr}.out 2>&1
mv WRFPRS$${fhr}.$${tmmark} $grib_filename
exit
